version: '3.8'

services:
  frontend:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
      - "6379:6379"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://localhost:6379
    depends_on:
      - redis
    networks:
      - pixelsqueeze-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - pixelsqueeze-network

volumes:
  redis-data:

networks:
  pixelsqueeze-network:
    driver: bridge